# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Skippy UI build

on:
  push:
    branches:
      - 'feat/**'
      - master
  pull_request:
    branches:
      - 'feat/**'
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./ui
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2

    - name: node${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install and npm run build 
      working-directory: ${{ env.working-directory}}
      run: |
          npm ci
          npm run build:ci
